# Generated by Django 2.0.6 on 2018-07-03 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta_Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principal.Etiqueta')),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Idea_Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principal.Idea')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('codigo', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materia_Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('semestre', models.IntegerField(default=1)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principal.Materia')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Materia_Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principal.Materia')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('descipcion', models.TextField(null=True)),
                ('repositorio', models.TextField(null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto_Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.Persona')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principal.Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Repositorio_Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(null=True)),
                ('link', models.TextField(null=True)),
                ('repositorio_id', models.IntegerField(null=True)),
                ('contribuyentes_url', models.TextField(null=True)),
                ('propietario', models.TextField(null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Persona')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='materia_proyecto',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principal.Proyecto'),
        ),
        migrations.AddField(
            model_name='idea_proyecto',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principal.Proyecto'),
        ),
        migrations.AddField(
            model_name='etiqueta_proyecto',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principal.Proyecto'),
        ),
    ]
